version: "3.9"

services:
  zeek-agent:
    build: .
    #image: nonvegan/fishy-tim-zeek-data-receiver
    environment:
      - KEYCLOAK_SERVER_AUTH_URL=*************************************
      - KEYCLOAK_REALM_NAME=***********
      - KEYCLOAK_CLIENT_ID=*****************
      - KEYCLOAK_CLIENT_SECRET=********************************
      - ALLOW_REQUESTS_KEYCLOAK_CLIENT_ID=***********
      - SPI_ENDPOINT_URL=******************************************
    ports:
        - "4000:4000"
